# Generated by Django 5.1.4 on 2024-12-24 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("location", models.CharField(max_length=200)),
                (
                    "job_types",
                    models.CharField(
                        choices=[
                            ("Full-time", "Full time"),
                            ("Part-time", "Part time"),
                        ],
                        max_length=50,
                    ),
                ),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("posted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recruter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.recruter",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.jobcategory",
                    ),
                ),
            ],
        ),
    ]
