services:
  web:
    image: mini-project
    ports:
      - 8000:8000
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  data:
